/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prestamos;

import java.awt.Color;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class interfaz_app extends javax.swing.JFrame {
    
    
    /**
     * Creates new form interfaz_app
     */
    public interfaz_app() {
        initComponents();
         setLocationRelativeTo(null);
        String[] diasSemana = {"1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"};
   
        String resp = (String) JOptionPane.showInputDialog(null, "Ingresa la fecha\nDia:", "Dia", JOptionPane.DEFAULT_OPTION, null, diasSemana, diasSemana[29]);
        int dia=Integer.parseInt(resp);
        String[] diasSemana1 = {"1","2","3","4","5","6","7","8","9","10","11","12"};
       
        String resp1 = (String) JOptionPane.showInputDialog(null, "Mes:", "Mes", JOptionPane.DEFAULT_OPTION, null, diasSemana1, diasSemana1[11]);
        int mes=Integer.parseInt(resp1);
        String[] diasSemana2 = {"2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021"};
       
        String resp2 = (String) JOptionPane.showInputDialog(null, "Año:", "Año", JOptionPane.DEFAULT_OPTION, null, diasSemana2, diasSemana2[11]);
        int aa = Integer.parseInt(resp2);
        global=new Fecha(dia,mes,aa);
        fechaL.setText(global.getDd()+"."+global.getMm()+"."+global.getAa());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        interfaz = new javax.swing.JTextArea();
        fechaL = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prestamos Angel");
        setBackground(new java.awt.Color(51, 51, 255));
        setSize(new java.awt.Dimension(500, 250));

        jToolBar1.setRollover(true);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prestamos/954564.png"))); // NOI18N
        jToggleButton1.setText("Guardar");
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton1);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prestamos/gratis-png-cruz-verde-signos-mas-y-menos-iconos-de-computadora-mas-iconos.png"))); // NOI18N
        jToggleButton2.setText("Nuevo");
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton2);

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prestamos/910714.png"))); // NOI18N
        jToggleButton3.setText("Prestamo");
        jToggleButton3.setFocusable(false);
        jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton3);

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prestamos/descarga.png"))); // NOI18N
        jToggleButton4.setText("Cobro");
        jToggleButton4.setFocusable(false);
        jToggleButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton4);

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prestamos/png-transparent-arrow-computer-icons-next-button-blue-trademark-internet-thumbnail.png"))); // NOI18N
        jToggleButton6.setText("Dia Siguiente");
        jToggleButton6.setFocusable(false);
        jToggleButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton6);

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prestamos/89413063-salir-del-icono-de-círculo-brillante-rojo-sobre-fondo-blanco.jpg"))); // NOI18N
        jToggleButton5.setText("Salir");
        jToggleButton5.setFocusable(false);
        jToggleButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton5);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prestamos/pngtree-calendar-icon-png-image_1521539.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Interfaz de Prestamos");

        interfaz.setColumns(20);
        interfaz.setRows(5);
        jScrollPane1.setViewportView(interfaz);

        fechaL.setFont(new java.awt.Font("OCR A Extended", 1, 11)); // NOI18N

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Prestamo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Cobro");
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Dia Siguiente");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Guardar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Buscar");

        jMenuItem13.setText("Busqueda Nombre");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem14.setText("Busqueda Telefono");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuItem15.setText("Busqueda Correo");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Prestatarios");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Mostrar ");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Prestamos");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Mostrar ");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reportes");

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Reporte Prestatarios");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Reporte Prestamos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Reporte Completo");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechaL, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(fechaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        capturaDatos();
        
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed
    public void capturaDatos(int a){
        String nombre = JOptionPane.showInputDialog("Ingresa tu nombre: ");
        String apellido = JOptionPane.showInputDialog("Ingresa tu primer apellido: ");
        String apellido2 = JOptionPane.showInputDialog("Ingresa tu segundo apellido: ");
        JOptionPane.showMessageDialog(null, "Bienvenido "+nombre+" "+apellido+" "+apellido2);
        String identidad = JOptionPane.showInputDialog("Ingresa tu numero de identidad: ");
        int id = Integer.parseInt(identidad);
        String telefono = JOptionPane.showInputDialog("Ingresa tu numero de telefono: ");
        long tel = Long.parseLong(telefono);
        String correo = JOptionPane.showInputDialog("Ingresa tu correo: ");
        Cliente cliente = new Cliente(id,nombre,apellido,apellido2,correo,tel);
        
        prestatarios.add(cliente);
        numPrestamo=1;
        interfaz.setText("Datos capturados correctamente "+nombre);   
        int resp = JOptionPane.showConfirmDialog(null,"¿Desea solicitar un prestamo?");
        if (JOptionPane.OK_OPTION == resp){
          capturaPrestamo();
        }
        else{
          JOptionPane.showMessageDialog(null,"Bienvenido "+nombre+" "+apellido);
        }
    }
    public void  capturaPrestamo(){
      String identidad = JOptionPane.showInputDialog("¿Cual es tu numero de indentificacion? ");
      int id = Integer.parseInt(identidad);
      for(Cliente i:prestatarios){
            if(i.identidad==id){
                String valor = JOptionPane.showInputDialog("Ingresa el valor del prestamo: ");
                Double cantidad = Double.parseDouble(valor);
                if(cantidad<=0){
                    JOptionPane.showMessageDialog(null,"La cantidad del prestamo debe ser mayor a 0 ");
                    continue;
                }
                boolean veri = i.compruebaSaldo(cantidad);
                if(veri==false){
                     JOptionPane.showMessageDialog(null,"La cantidad del prestamo excede el monto maximo 10,000. ");
                    continue;
                }
                String[] diasSemana = {"3","4","5","6"};
                Icon icono = new ImageIcon(getClass().getResource("pngtree-calendar-icon-png-image_1521539.jpg"));
                String cuotas = (String) JOptionPane.showInputDialog(null, "Numero de cuotas", "Cuotas", JOptionPane.DEFAULT_OPTION, icono, diasSemana, diasSemana[3]);
                int meses = Integer.parseInt(cuotas);
                boolean verifica = comprobarAutorizacion();
                if(verifica){
                    Fecha auto = new Fecha(global.dd,global.mm,global.aa);
                    Fecha entrega = new Fecha(global.dd,global.mm,global.aa);
                    entrega.obtenerFechaEntrega();
                    Prestamo presta = new Prestamo(numPrestamo,cantidad,auto,entrega,meses);
                    if(meses==3){
                        presta.tresCuotas();
                    }
                    if(meses==4){
                        presta.cuatroCuotas();
                    }
                    if(meses==5){
                        presta.cincoCuotas();
                    }
                    if(meses==6){
                        presta.seisCuotas();
                    }
                    i.prestamo.add(presta);
                    numPrestamo++;
                    
                }
                interfaz.setText("Datos capturados: \nNombre: "+i.getNombre()+" "+i.getApellido()+" "+i.getApellido2()+
                        "\nID: "+i.getIdentidad()+"\nCorreo: "+i.getCorreo()+"\nTelefono: "+i.getTelefono()+
                        "\nDatos de prestamo: \n"+i.getPrestamo());
                Reporteprestamos=Reporteprestamos+"Prestamo #"+num+"\n";
                Reporteprestamos=Reporteprestamos+i.getPrestamo();
                archivo=archivo+"\n\n\n"+interfaz.getText();
                
                num++;
            }
            
            
        }
    }
    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
      capturaPrestamo();
      
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        //for(Cliente i:prestatarios){
        //interfaz.setText("Los clientes son: \n"+i.toString());
        //}
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        global.dd++;
        global.verificaFecha();
        fechaL.setText(global.getDd()+"."+global.getMm()+"."+global.getAa());
        boolean veri,veri2;
        for(Cliente i:prestatarios){
        
        veri2 = i.buscarFecha2(global.dd,global.mm);
        if (veri2==true){
           JOptionPane.showMessageDialog(null, "Se ha entregado un prestamo a "+i.getNombre()+" "+i.getApellido()+".");
           continue;
        }
        veri = i.buscarFecha3(global.dd,global.mm);
        if (veri==true){
           JOptionPane.showMessageDialog(null, "El prestatario "+i.getNombre()+" "+i.getApellido()+" debe realizar un pago hoy.");
            
        }
        
        }
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
     boolean veri;
        for(Cliente i:prestatarios){
        veri = i.buscarFecha(global.dd,global.mm);
        if (veri==true){
           JOptionPane.showMessageDialog(null, "Cobro realizado a "+i.getNombre()+" "+i.getApellido());
            interfaz.setText("Datos capturados: \nNombre: "+i.getNombre()+" "+i.getApellido()+" "+i.getApellido2()+
                        "\nID: "+i.getIdentidad()+"\nCorreo: "+i.getCorreo()+"\nTelefono: "+i.getTelefono()+
                        "\nDatos de prestamo: \n"+i.getPrestamo());
            archivo=archivo+"\n\n\nPAGO REALIZADO\n"+interfaz.getText();
        }
    }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
       int resp = JOptionPane.showConfirmDialog(null,"¿Desea salir sin guardar?");
      if (JOptionPane.OK_OPTION == resp){
          System.exit(WIDTH);
      }
      else{
          JOptionPane.showMessageDialog(null,"Presione el boton Guardar.");
      }
        
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        FileWriter fichero = null;
        PrintWriter pw = null;
        try
        {
            fichero = new FileWriter("Registro de Prestamos.txt");
            pw = new PrintWriter(fichero);

          
                pw.println("\t\t\tPrestamos el Ahora tu me debes\n"+archivo);
                JOptionPane.showMessageDialog(null, "Datos Guardados Exitosamente.");
        
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
           try {
           // Nuevamente aprovechamos el finally para 
           // asegurarnos que se cierra el fichero.
           if (null != fichero)
              fichero.close();
           } catch (Exception e2) {
              e2.printStackTrace();
           }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         capturaDatos();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
      
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        capturaPrestamo();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        global.dd++;
        global.verificaFecha();
        fechaL.setText(global.getDd()+"."+global.getMm()+"."+global.getAa());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FileWriter fichero = null;
        PrintWriter pw = null;
        try
        {
            fichero = new FileWriter("Registro de Prestamos.txt");
            pw = new PrintWriter(fichero);

          
                pw.println("\t\t\tPrestamos el Ahora tu me debes\n"+archivo);
                JOptionPane.showMessageDialog(null, "Datos Guardados Exitosamente.");
        
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
           try {
           // Nuevamente aprovechamos el finally para 
           // asegurarnos que se cierra el fichero.
           if (null != fichero)
              fichero.close();
           } catch (Exception e2) {
              e2.printStackTrace();
           }
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        String clientes="";
        int num = 1;
        for(Cliente i:prestatarios){   
            clientes=clientes+"Prestatario #"+num+++": \n";
            clientes = clientes+"Nombre: "+i.getNombre()+" "+i.getApellido()+" "+i.getApellido2()+"\n";
            clientes = clientes+"Correo: "+i.getCorreo();
            clientes = clientes+"\nCelular: "+i.getTelefono()+"\n\n";
        }
        interfaz.setText(clientes);
        Reporteclientes=clientes;
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        interfaz.setText(Reporteprestamos);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        FileWriter fichero = null;
        PrintWriter pw = null;
        try
        {
            fichero = new FileWriter("Registro de Prestatarios.txt");
            pw = new PrintWriter(fichero);

          
                pw.println("\t\t\tPrestamos el Ahora tu me debes\n\n"+Reporteclientes);
                JOptionPane.showMessageDialog(null, "Registro Generado.");
        
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
           try {
           // Nuevamente aprovechamos el finally para 
           // asegurarnos que se cierra el fichero.
           if (null != fichero)
              fichero.close();
           } catch (Exception e2) {
              e2.printStackTrace();
           }
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FileWriter fichero = null;
        PrintWriter pw = null;
        try
        {
            fichero = new FileWriter("Registro de Prestamos.txt");
            pw = new PrintWriter(fichero);

          
                pw.println("\t\t\tPrestamos el Ahora tu me debes\n\n"+Reporteprestamos);
                JOptionPane.showMessageDialog(null, "Registro Generado.");
        
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
           try {
           // Nuevamente aprovechamos el finally para 
           // asegurarnos que se cierra el fichero.
           if (null != fichero)
              fichero.close();
           } catch (Exception e2) {
              e2.printStackTrace();
           }
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
         FileWriter fichero = null;
        PrintWriter pw = null;
        try
        {
            fichero = new FileWriter("Registro Completo de Prestamos.txt");
            pw = new PrintWriter(fichero);

          
                pw.println("\t\t\tPrestamos el Ahora tu me debes\n"+archivo);
                JOptionPane.showMessageDialog(null, "Datos Guardados Exitosamente.");
        
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
           try {
           // Nuevamente aprovechamos el finally para 
           // asegurarnos que se cierra el fichero.
           if (null != fichero)
              fichero.close();
           } catch (Exception e2) {
              e2.printStackTrace();
           }
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
      String identidad = JOptionPane.showInputDialog("Ingresa el telefono del prestatario ");
      int aux=0;
      long tel = Long.parseLong(identidad);
      for(Cliente i:prestatarios){
            if(i.telefono==tel){
               JOptionPane.showMessageDialog(null, "Busqueda exitosa");
               interfaz.setText("Datos del prestatario: \nNombre: "+i.getNombre()+" "+i.getApellido()+" "+i.getApellido2()+
                        "\nID: "+i.getIdentidad()+"\nCorreo: "+i.getCorreo()+"\nTelefono: "+i.getTelefono()+
                        "\nDatos de prestamo: \n"+i.getPrestamo()); 
               aux=1;
            }
      }
      if(aux==0)JOptionPane.showMessageDialog(null, "No se encontró conicidencias.");
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
     String identidad = JOptionPane.showInputDialog("Ingresa el nombre del prestatario ");
     int aux=0; 
     for(Cliente i:prestatarios){
            if(i.nombre.equals(identidad)){
               JOptionPane.showMessageDialog(null, "Busqueda exitosa");
               interfaz.setText("Datos del prestatario: \nNombre: "+i.getNombre()+" "+i.getApellido()+" "+i.getApellido2()+
                        "\nID: "+i.getIdentidad()+"\nCorreo: "+i.getCorreo()+"\nTelefono: "+i.getTelefono()+
                        "\nDatos de prestamo: \n"+i.getPrestamo()); 
               aux=1;
            }
      }
      if(aux==0)JOptionPane.showMessageDialog(null, "No se encontró conicidencias.");
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        String identidad = JOptionPane.showInputDialog("Ingresa el correo del prestatario ");
      int aux=0;
        for(Cliente i:prestatarios){
            if(i.correo.equals(identidad)){
               JOptionPane.showMessageDialog(null, "Busqueda exitosa");
               interfaz.setText("Datos del prestatario: \nNombre: "+i.getNombre()+" "+i.getApellido()+" "+i.getApellido2()+
                        "\nID: "+i.getIdentidad()+"\nCorreo: "+i.getCorreo()+"\nTelefono: "+i.getTelefono()+
                        "\nDatos de prestamo: \n"+i.getPrestamo()); 
               aux=1;
            }
      }
      if(aux==0)JOptionPane.showMessageDialog(null, "No se encontró conicidencias.");
    }//GEN-LAST:event_jMenuItem15ActionPerformed
public boolean comprobarAutorizacion(){
    if(global.dd>20){
        JOptionPane.showMessageDialog(null, "¡No se puede autorizar el prestamo!"); 
        interfaz.setText("Un prestamo solo se puede autorizar los primeros 20 dias del mes.");
        return false;
    }else
        return true;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_app().setVisible(true);
            }
        });
    }
    String archivo="";
    String Reporteprestamos="";
    String Reporteclientes="";
    Fecha global;
    int numPrestamo,num=1;
    ArrayList<Cliente> prestatarios = new ArrayList<Cliente>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fechaL;
    private javax.swing.JTextArea interfaz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
